Models/Contract.cs
using System;
using System.Collections.Generic;

namespace Software.Models
{
    public partial class Contract
    {
        public uint ContractId { get; set; }
        public uint CustomerId { get; set; }
        public DateOnly ContractDate { get; set; }
        public uint Cost { get; set; }

        public virtual Customer Customer { get; set; } = null!;
        public virtual SoftwareProduct? SoftwareProduct { get; set; }
    }
}

Models/Customer.cs
using System;
using System.Collections.Generic;

namespace Software.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Contracts = new HashSet<Contract>();
        }

        public uint CustomerId { get; set; }
        public string? CustomerName { get; set; }
        public string? Address { get; set; }
        public string? PhoneNumber { get; set; }
        public string? ContactPerson { get; set; }

        public virtual ICollection<Contract> Contracts { get; set; }
    }
}

Models/DevelopmentPlayer.cs
using System;
using System.Collections.Generic;

namespace Software.Models
{
    public partial class DevelopmentPlayer
    {
        public uint PlayerId { get; set; }
        public uint? ProductId { get; set; }
        public uint? EmployeeId { get; set; }
        public string? EmployeeRole { get; set; }

        public virtual Employee? Employee { get; set; }
        public virtual SoftwareProduct? Product { get; set; }
    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;

namespace Software.Models
{
    public partial class Employee
    {
        public Employee()
        {
            DevelopmentPlayers = new HashSet<DevelopmentPlayer>();
        }

        public uint EmployeeId { get; set; }
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string? MiddleName { get; set; }
        public string? PhoneNumber { get; set; }
        public string? Email { get; set; }
        public DateOnly HireDate { get; set; }
        public uint Salary { get; set; }

        public virtual ICollection<DevelopmentPlayer> DevelopmentPlayers { get; set; }
    }
}

Models/ProductType.cs
namespace Software.Models
{
    public partial class ProductType
    {
        public ProductType()
        {
            SoftwareProducts = new HashSet<SoftwareProduct>();
        }

        public string TypeId { get; set; } = null!;
        public string? Name { get; set; }

        public virtual ICollection<SoftwareProduct> SoftwareProducts { get; set; }
    }
}

Models/SoftwareProduct.cs
namespace Software.Models
{
    public partial class SoftwareProduct
    {
        public SoftwareProduct()
        {
            DevelopmentPlayers = new HashSet<DevelopmentPlayer>();
        }

        public uint ProductId { get; set; }
        public string ProductName { get; set; } = null!;
        public string? TypeId { get; set; }
        public string Version { get; set; } = null!;
        public DateTime? ReleaseDate { get; set; }
        public uint? ContractId { get; set; }

        public virtual Contract? Contract { get; set; }
        public virtual ProductType? Type { get; set; }
        public virtual ICollection<DevelopmentPlayer> DevelopmentPlayers { get; set; }
    }
}

Controllers/SoftwareController.cs
using Software.Data;
using Software.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DBShananin.Controllers
{
    public enum SortState
    {
        IdAsc,
        IdDesc,
        NameAsc,
        NameDesc,
        TypeAsc,
        TypeDesc,
        VerAsc,
        VerDesc,
        DateAsc,
        DateDesc,
    }

    public class SoftwareController : Controller
    {
        private SoftwareContext _db;

        public SoftwareController(SoftwareContext db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string name, SortState order = SortState.IdAsc)
        {
            IQueryable<SoftwareProduct> products = _db.SoftwareProducts.Include(p => p.Type);

            if (!string.IsNullOrEmpty(name))
            {
                products = products.Where(p => p.ProductName.Contains(name));
            }

            ViewData["IdSort"]   =  order == SortState.IdAsc    ? SortState.IdDesc   : SortState.IdAsc;
            ViewData["NameSort"] =  order == SortState.NameAsc  ? SortState.NameDesc : SortState.NameAsc;
            ViewData["TypeSort"] =  order == SortState.TypeAsc  ? SortState.TypeDesc : SortState.TypeAsc;
            ViewData["VerSort"]  =  order == SortState.VerAsc   ? SortState.VerDesc  : SortState.VerAsc;
            ViewData["DateSort"] =  order == SortState.DateAsc  ? SortState.DateDesc : SortState.DateAsc;

            products = order switch
            {
                SortState.IdDesc    => products.OrderByDescending(p => p.ProductId),
                SortState.NameAsc   => products.OrderBy(p => p.ProductName),
                SortState.NameDesc  => products.OrderByDescending(p => p.ProductName),
                SortState.TypeAsc   => products.OrderBy(p => p.Type.Name),
                SortState.TypeDesc  => products.OrderByDescending(p => p.Type.Name),
                SortState.VerAsc    => products.OrderBy(p => p.Version),
                SortState.VerDesc   => products.OrderByDescending(p => p.Version),
                SortState.DateAsc   => products.OrderBy(p => p.ReleaseDate),
                SortState.DateDesc  => products.OrderByDescending(p => p.ReleaseDate),
                _ => products.OrderBy(p => p.ProductId),
            };

            return View(await products.ToListAsync());
        }

        public IActionResult CreateProduct()
        {
            ViewBag.TypeId = new SelectList(_db.ProductTypes.Select(type => type.Name));
            ViewBag.ContractId = new SelectList(_db.Contracts.Select(contract => contract.ContractId));
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(SoftwareProduct product)
        {
            _db.SoftwareProducts.Add(product);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditProduct(int? id)
        {
            if (id == null) return NotFound();

            ViewBag.TypeId = new SelectList(_db.ProductTypes.Select(type => type.Name));
            ViewBag.ContractId = new SelectList(_db.Contracts.Select(contract => contract.ContractId));
            var product = await _db.SoftwareProducts.SingleOrDefaultAsync(p => p.ProductId == id);
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> EditProduct(SoftwareProduct product)
        {
            _db.SoftwareProducts.Update(product);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteProduct(int? id)
        {
            if (id == null) return NotFound();

            var product = await _db.SoftwareProducts.SingleOrDefaultAsync(p => p.ProductId == id);
            _db.SoftwareProducts.Remove(product);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

Views/Software/CreateProduct.cshtml
@model Software.Models.SoftwareProduct

@{
    ViewData["Title"] = "CreateProduct";
}

<h1>CreateProduct</h1>

<h4>SoftwareProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateProduct" asp-controller="Software" method="post">
            <div class="form-group">
                <label asp-for="ProductName" class="control-label">Название</label>
                <input asp-for="ProductName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label">Тип</label>
                <select asp-for="TypeId" class ="form-control" asp-items="ViewBag.TypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Version" class="control-label">Версия</label>
                <input asp-for="Version" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label">Дата релиза</label>
                <input type="date" asp-for="ReleaseDate" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ContractId" class="control-label">Договор</label>
                <select asp-for="ContractId" class ="form-control" asp-items="ViewBag.ContractId"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Отправить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Software/EditProduct.cshtml
@model Software.Models.SoftwareProduct

@{
    ViewData["Title"] = "EditProduct";
}

<h1>CreateProduct</h1>

<h4>SoftwareProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditProduct" asp-controller="Software" asp-route-productid="@Model.ProductId" method="post">
            <div class="form-group">
                <label asp-for="ProductName" class="control-label">Название</label>
                <input asp-for="ProductName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label">Тип</label>
                <select asp-for="TypeId" class ="form-control" asp-items="ViewBag.TypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Version" class="control-label">Версия</label>
                <input asp-for="Version" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label">Дата релиза</label>
                <input type="date" asp-for="ReleaseDate" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ContractId" class="control-label">Договор</label>
                <select asp-for="ContractId" class ="form-control" asp-items="ViewBag.ContractId"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Отправить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Software/Index.cshtml
@model IEnumerable<Software.Models.SoftwareProduct>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<div>
    <a asp-action="CreateProduct">Добавить запись</a> |
    <form asp-action="Index" asp-controller="Software" method="get">
        <div class="form-inline form-group">
            <label class="control-label">Поиск программы: </label>
            <input name="name" />

            <input type="submit" value="Искать" class="btn btn-default" />
        </div>
    </form>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th><a asp-action="Index" asp-route-order="@ViewBag.IdSort">Id</a></th>
                <th><a asp-action="Index" asp-route-order="@ViewBag.NameSort">Название</a></th>
                <th><a asp-action="Index" asp-route-order="@ViewBag.TypeSort">Тип</a></th>
                <th><a asp-action="Index" asp-route-order="@ViewBag.VerSort">Версия</a></th>
                <th><a asp-action="Index" asp-route-order="@ViewBag.DateSort">Дата релиза</a></th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var product in Model)
                {
                    <tr>
                        <td>@product.ProductId</td>
                        <td>@product.ProductName</td>
                        <td>@product.Type</td>
                        <td>@product.Version</td>
                        <td>@product.ReleaseDate</td>
                        <td><a asp-action="EditProduct" asp-route-id="@product.ProductId">Изменить</a></td>
                        <td><a asp-action="DeleteProduct" asp-route-id="@product.ProductId">Удалить</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>